# import requests
# from bs4 import BeautifulSoup
#
# response = requests.get("https://lombard-perspectiva.ru/products")
# soup = BeautifulSoup(response.text, 'html.parser')
# products = soup.find_all("div", class_="container")
# for i in products:
#     print(i)


WATCHES = [
    "Неизвестно",
    "AET REMOULD",
    "Alain Silberstein",
    "A. Lange & Sohne",
    "Antoine Preziuso",
    "Arnold & Son",
    "ARTYA",
    "Audemars Piguet",
    "BADOLLET",
    "Bell & Ross",
    "Blancpain",
    "BLU",
    "Breguet",
    "Breitling",
    "Bvlgari",
    "Carl F.Bucherer",
    "Cartier",
    "CHAUMET",
    "Chopard",
    "Christophe Claret",
    "Chronoswiss",
    "Clerk",
    "Corum",
    "Cvstos",
    "Czapek",
    "Daniel Roth",
    "De Bethune",
    "De grisogono",
    "Delaneau",
    "De Witt",
    "EDOUARD KOEHN",
    "FP Journe",
    "Franck Muller",
    "Franc Vila",
    "Frédéric Jouvenot",
    "Frederique Constant",
    "Gerald Charles",
    "Gerald Genta",
    "Girard Perregaux",
    "Glashutte Original",
    "GRAFF",
    "Graham",
    "Greubel Forsey",
    "Harry Winston",
    "HD 3",
    "H. Moser & Cie",
    "Hublot",
    "Ice Link",
    "IWC",
    "Jacob & Co",
    "Jaeger LeCoultre",
    "Jaquet Droz",
    "Jean Dunand",
    "JeanRichard",
    "Jorg Hysek",
    "Laurent Ferrier",
    "L'epee",
    "Longines",
    "Louis Moinet",
    "Maikou Bode",
    "Maurice Lacroix",
    "MB&F",
    "Nivrel",
    "Omega",
    "Panerai",
    "Parmigiani Fleurier",
    "Patek Philippe",
    "Perrelet",
    "Piaget",
    "Pierre Kunz",
    "Quinting",
    "RAFFAEL PAPIAN",
    "Ressence",
    "Richard Mille",
    "Roger Dubuis",
    "Rolex",
    "Romain Jerome",
    "Tag Heuer",
    "THOMAS PRESCHER",
    "Tiffany & Co",
    "Tudor",
    "Ulysse Nardin",
    "Urwerk",
    "Vacheron Constantin",
    "Van Cleef & Arpels",
    "Wyler",
    "Zenith"
]

print(len(WATCHES))
release: python manage.py migrate && python manage.py load_initial_data
