# Generated by Django 5.2 on 2025-04-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0002_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, null=True, verbose_name="Цена"),
        ),
    ]
