# Generated by Django 5.2 on 2025-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_alter_filterpreset_options_alter_filterpreset_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.ManyToManyField(blank=True, related_name='cities', to='watch.city', verbose_name='Наличие в городах'),
        ),
    ]
