# Generated by Django 5.2 on 2025-05-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0011_rename_city_filterpreset_in_stock_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="cities",
            new_name="city",
        ),
    ]
