# Generated by Django 5.2 on 2025-05-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0013_remove_product_city_product_cities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "verbose_name": "Бренд часов",
                "verbose_name_plural": "Бренды часов",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
    ]
