# Generated by Django 5.2 on 2025-05-13 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0016_remove_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[^:]+$', 'Название города не должно содержать двоеточий')]),
        ),
    ]
