# Generated by Django 5.2 on 2025-05-22 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0020_watchitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchitem",
            name="price_id",
        ),
        migrations.AddField(
            model_name="watchitem",
            name="price_usd",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена (USD)",
            ),
        ),
    ]
