# Generated by Django 5.2 on 2025-05-23 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0021_remove_watchitem_price_id_watchitem_price_usd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WatchItem",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="price_usd",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Цена (USD)",
            ),
        ),
    ]
