# Generated by Django 5.2 on 2026-03-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0022_delete_watchitem_remove_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(verbose_name="URL изображения")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="watch.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное фото",
                "verbose_name_plural": "Дополнительные фото",
                "ordering": ["order"],
            },
        ),
    ]
