# Generated by Django 5.2 on 2026-03-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0023_productimage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product"], name="watch_produ_product_add220_idx"
            ),
        ),
    ]
