# Generated by Django 5.2 on 2026-03-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0024_productimage_watch_produ_product_add220_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="telegram_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отправлено в Telegram"
            ),
        ),
    ]
