# Generated by Django 5.2 on 2026-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0025_product_telegram_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bezel",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Безель"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="caliber",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Калибр"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="case_diameter",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Диаметр корпуса"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="case_material",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Материал корпуса"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="collection",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Коллекция"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="condition_detail",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Состояние (детально)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dial_color",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Цвет циферблата"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="functions",
            field=models.TextField(blank=True, null=True, verbose_name="Функции"),
        ),
        migrations.AddField(
            model_name="product",
            name="glass",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Стекло"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="movement_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Тип механизма"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="power_reserve",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Запас хода"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ref",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Референс"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="strap_material",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Материал ремешка"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="water_resistance",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Водонепроницаемость"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="комплектация",
            field=models.TextField(blank=True, null=True, verbose_name="Комплектация"),
        ),
    ]
