# Generated by Django 5.2 on 2026-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0026_product_bezel_product_caliber_product_case_diameter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="model",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Модель"
            ),
        ),
    ]
