# Generated by Django 5.2 on 2026-03-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watch", "0027_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_text",
            field=models.CharField(
                blank=True,
                help_text="Например: 'По запросу', 'Договорная' и т.д.",
                max_length=50,
                null=True,
                verbose_name="Цена (текст)",
            ),
        ),
    ]
