{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "project1-secrets",
    "namespace": "project1"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "project1-secrets",
        "namespace": "project1"
      }
    },
    "encryptedData": {
      "django-key": "AgDRIVMVOasYn4OtITpnbGpLgt3NumwIrp3ymp6wxOnJu9X8cC1xwCjdcBzuW5fQlxQotawMv6Vgiw89ddJgu7B2CCs+XWy+eb5Rt5Di2l5wlg1AF+E1xe5Vq7OAWbsLpN71jdWE7HaGPil1UldkvEUoIkUQBQQLgkGhyuQgDR2M8wP6QUlnnso3iZpCYp5z6aBIQQ88amerdzq9exGiIsw/oKEc0Kcc2kLNFDwEnuxscb0SO5a11/mqXGfhK6gciGfFn7yLbR+qwnrF6UhRtBv59owwwMSRz8CU+W9gWIfFsiQTaGBvbVnazAYNEIz72tZAGEOI/doD/PDDFHpl4bbH77TCQfhfG2tov53MgPR0tvBRbKJwnHUYalTnDkkunW5Yvb7rULbRQGEf633ju12XLMSDwgiC39JKkB546QRyb0JtVsiCN6hGQ8ZFGgumyG5ibJiY9u1C0bOKGQ2IPGLx5xMzIjsUt6G54DaxFrcDP0LDL0FwukJk04/A775mdeX+zl36CDnPP/SRcF51fZfkGuxENDErJ0CSxdxWkvpwh9T6GjY/rM7+I4CMG6IzWaAyZ/WEoRTYufLhrTvLjnU+N5ElYMLkguwTuwnT4xYZVH6uY20b7SgoYypABtZAjG6V6i/SlnUoTdMuOVt5kDMloIW2wltHlK3bNd2/FAeCV4yV8I3swAVwRClWI2g9lHotjAwXL7sQTs7ZxOu/lvebfvWLswm/+FrphyBg22jzqRtijA+qG+OG8bS/Ow8mjr4KiQ=="
    }
  }
}
