"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.
"""

import os
import sys
from pathlib import Path

import dj_database_url
from loguru import logger

import environ
# from dotenv import load_dotenv  # Для загрузки переменных окружения

# Инициализация окружения ДО использования
env = environ.Env(
    # Установите дефолтные значения
    DEBUG=(bool, True),
)
# Настройка базовой директории
BASE_DIR = Path(__file__).resolve().parent.parent

# Инициализация окружения
# Чтение .env файла
env.read_env(BASE_DIR / ".env")
# env = environ.Env(DEBUG=(bool, False))
#DEBUG = env.bool("DEBUG", default=True) 
DEBUG = True
# environ.Env.read_env(BASE_DIR / ".env")  # <-- важно
TEMPLATE_DIR = BASE_DIR / "templates"

# с fallback значениями:
SECRET_KEY = env("SECRET_KEY")
# SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = env.bool("DEBUG", default=False)
# Для ALLOWED_HOSTS
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "0.0.0.0",
    "192.168.1.139",
    ".ngrok-free.app",
    ".ngrok-free.dev",
    "vorticose-reta-knurled.ngrok-free.dev",
    "188.226.37.12",                                    # ваш публичный IP
    "project1.188.226.37.12.nip.io",                   # ваш ingress домен
    ".nip.io",                                          # все nip.io домены
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:10000",
    "http://127.0.0.1:10000",
    "https://*.ngrok-free.app",
    "https://*.ngrok-free.dev",
    "https://vorticose-reta-knurled.ngrok-free.dev",
    "http://188.226.37.12",                             # публичный IP
    "http://project1.188.226.37.12.nip.io",             # ingress домен
    "http://*.nip.io",                                  # все nip.io домены
]
# Render проксирует HTTPS, и без этого Django может думать, что это HTTP
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# # Чтобы на Render автоматически шёл редирект с HTTP на HTTPS.
# SECURE_SSL_REDIRECT = not DEBUG


# Только для локального запуска!
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
SECURE_SSL_REDIRECT = False

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Third-party apps
    # "crispy_forms",
    # "crispy_bootstrap5",
    "crispy_forms",
    "crispy_tailwind",
    "corsheaders",
    "django_filters",
    # Local apps
    "watch.apps.WatchConfig",
]
CORS_ALLOWED_ORIGINS = [
    "https://yourdomain.com",
    "http://localhost:8000",
    "http://localhost:8080",
]  # Или конкретные домены

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# if DEBUG:
#     DATABASES = {
#         'default': env.db(default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
#     }
# else:
#     DATABASES = {
#         'default': env.db('DATABASE_URL')
#     }
# DATABASES = {
#     "default": dj_database_url.config(
#         default="sqlite:///" + str(BASE_DIR / "db.sqlite3"),
#         conn_max_age=600,
#         ssl_require=not DEBUG,
#     )
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Replace the SQLite DATABASES configuration with PostgreSQL:
# DATABASES = {
#     'default': dj_database_url.config(
#         default=os.getenv('DATABASE_URL'),  # Чтение из переменной Railway
#         conn_max_age=600,
#         ssl_require=not DEBUG  # SSL для production
#     )
# }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Asia/Yekaterinburg"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # Исправлено: было STATICFILES_DIR
STATIC_ROOT = BASE_DIR / "staticfiles"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/



# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
   
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Loguru configuration
logger.remove()  # Remove default handler
logger.add(
    sys.stdout,
    format="<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>",
    level="DEBUG" if DEBUG else "INFO",
    backtrace=True,
    diagnose=True,
)
# Для production используйте Redis/Memcached
CACHES = (
    {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": env("REDIS_URL", default="redis://localhost:6379/1"),
        }
    }
    if not DEBUG
    else {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
)
# Если нужно сохранять логи в файл, добавьте:
# logger.add("logs/file_{time}.log", rotation="10 MB", retention="10 days")
# Настройки HTTPS
# if not DEBUG:
#     SECURE_HSTS_SECONDS = 3600
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_SECURE = True


# settings/production.py
# from .base import *
#
# DEBUG = False
# ALLOWED_HOSTS = ['yourdomain.com', 'api.yourdomain.com']
# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True




# config/settings.py

# Контакты для Telegram постов
CONTACTS = [
    {"address": "<b>Наши контакты:</b> @Genesislab"},
    {
        "address": "<b>Екатеринбург, ул. Маршала Жукова 13</b>",
        "tel": "+7(982)663-99-99",
        "wa_link": "https://wa.me/79826639999"
    },
    {
        "address": '<b>Екатеринбург, ул. Сакко и Ванцетти 74</b>, Торговая галерея "LUXURY"',
        "tel": "+7(982)699-66-66",
        "wa_link": "https://wa.me/79826996666"
    }
]


# Настройки для парсера
MAX_PHOTOS = 10
CUSTOM_PHOTOS = []  # Список URL кастомных фото
CUSTOM_VIDEOS = []  # Список URL кастомных видео